name: Remote SSH Command
on:
  push:
    branches: ["konsinyasi"]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Execute remote SSH commands using password
        uses: appleboy/ssh-action@v1
        with:
          host: 147.139.163.50
          username: root
          password: D3v3lop3r#
          port: 22
          script: whoami
