# name: Remote SSH Command
# on:
#   push:
#     branches: ["konsinyasi"]
# jobs:
#   build:
#     name: Build
#     runs-on: ubuntu-latest
#     steps:
#       - name: Execute remote SSH commands using password
#         uses: appleboy/ssh-action@v1
#         with:
#           host: 147.139.163.50
#           username: root
#           password: D3v3lop3r#
#           port: 22
#           script: whoami

name: Deploy Nuxt 3

on:
  push:
    branches: ["konsinyasi"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22

      # - name: Install dependencies
      #   run: npm i

      # - name: Build Nuxt 3
      #   run: npm run build

      # - name: Tar build output
      #   run: tar -czf output.tar.gz .output

      # # Upload artifact ke server
      # - name: Copy files via SSH
      #   uses: appleboy/ssh-action@v1
      #   with:
      #     host: ${{ secrets.SSH_HOST }}
      #     username: ${{ secrets.SSH_USER }}
      #     password: ${{ secrets.SSH_PASSWORD }}
      #     port: ${{ secrets.SSH_PORT }}
      #     source: "output.tar.gz"
      #     target: "${{ secrets.APP_DIR }}/output.tar.gz"

      # Eksekusi di server
      - name: Deploy di server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.APP_DIR }}
            export NVM_DIR="$HOME/.nvm"
            source "$NVM_DIR/nvm.sh"
            pm2 stop 5


     #       # rm -rf .output
     #       # tar -xzf output.tar.gz
     #       # rm output.tar.gz
     #       # pm2 restart "trums-FE | 8008"
     #       # pm2 save
